# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventtag',
            options={'verbose_name': 'Event Tag', 'verbose_name_plural': 'Event Tags'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_location_address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_tag',
        ),
        migrations.AddField(
            model_name='event',
            name='event_facebook_url',
            field=models.CharField(default='https://facebook.com', max_length=256, verbose_name='Facebook Event URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.TextField(max_length=768, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_location_name',
            field=models.CharField(default='Heavener Hall 270', max_length=256, verbose_name='Location Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=None, max_length=128, unique=True, verbose_name='URL (Avoid Editing)'),
        ),
    ]
