# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='leader_image',
            field=models.ImageField(blank=True, upload_to='membership'),
        ),
    ]
