# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_coordinator_coordinator_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='coordinator_bio',
            field=models.TextField(default='bio', max_length=2048, verbose_name='Bio'),
        ),
    ]
