# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.TextField(max_length=1024, verbose_name='Subtitle')),
                ('email_address', models.CharField(max_length=512, verbose_name='Email Button Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_name', models.CharField(max_length=128, verbose_name='Company Name')),
                ('url_name', models.CharField(max_length=512, verbose_name='Company URL')),
                ('picture_name', models.ImageField(upload_to='logos', verbose_name='Company Image')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorshipLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=128, verbose_name='Font Awesome Icon')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('details', models.TextField(max_length=2048, verbose_name='Details')),
            ],
        ),
    ]
