# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterModules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_tile', models.CharField(max_length=256, verbose_name='Title')),
                ('module_icon', models.CharField(max_length=128, verbose_name='Font Awesome Icon')),
                ('module_description', models.TextField(max_length=1024, verbose_name='Description')),
            ],
        ),
    ]
