# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SemesterModules',
            new_name='SemesterModule',
        ),
    ]
