# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170316_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=128, verbose_name='Font Awesome Icon')),
                ('button_text', models.CharField(max_length=128, verbose_name='Button Text')),
                ('button_link', models.CharField(max_length=1024, verbose_name='Button Link')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.TextField(max_length=1024, verbose_name='Subtitle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextBlurb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=128, verbose_name='Font Awesome Icon')),
                ('blurb_title', models.CharField(max_length=128, verbose_name='Blurb Title')),
                ('blurb_text', models.CharField(max_length=512, verbose_name='Blurb Text')),
            ],
        ),
    ]
