# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170316_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semestermodule',
            old_name='module_tile',
            new_name='module_title',
        ),
    ]
