# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-23 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=128)),
                ('event_description', models.TextField(max_length=768)),
                ('event_location_name', models.CharField(default='Heavener Hall 250', max_length=256)),
                ('event_location_address', models.CharField(default='1325 W University Ave, Gainesville, FL 32601', max_length=256)),
                ('event_date', models.DateTimeField(verbose_name='event date')),
                ('slug', models.SlugField(default=None, max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_tag', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.EventTag'),
        ),
    ]
