# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160917_1010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventTag',
        ),
    ]
