# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170109_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_location_name',
            field=models.CharField(default='Heavener Hall 150', max_length=256, verbose_name='Location Name'),
        ),
    ]
