# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator_title', models.CharField(max_length=128, verbose_name='Coordinator Title')),
                ('coordinator_name', models.CharField(max_length=256, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Coordinator',
                'verbose_name_plural': 'Coordinators',
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_title', models.CharField(max_length=128, verbose_name='Leadership Title')),
                ('leader_name', models.CharField(max_length=256, verbose_name='Name')),
                ('leadership_bio', models.TextField(max_length=2048, verbose_name='Bio')),
            ],
            options={
                'verbose_name': 'Leader',
                'verbose_name_plural': 'Leaders',
            },
        ),
        migrations.AddField(
            model_name='coordinator',
            name='coordinator_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.Leader'),
        ),
    ]
