# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_url', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('resource_name', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('resource_image', models.FileField(blank=True, default=None, max_length=256, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_tag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.ResourceTag'),
        ),
    ]
