# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_image',
            field=models.FileField(blank=True, default=None, max_length=256, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_name',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_url',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_tag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.ResourceTag'),
        ),
    ]
